### ISSUE TITLE
Final N@TM Project Plan

### ISSUE THREAD

**Issue by advikg** [spooketti/TetrisVS#1]
# Extension of Tetris Web Game - Leaderboard
By May 22nd(Wednesday):
- [x] Ensure backend works with database functionality
- [x] Add users and leaderboard tables to allow for score saving under a secure password
- [ ] Frontend login functionality
All of the above allows a user to login and save scores/view high scores

By May 27th(Monday):
- [x] Sorting/searching will be used for the leaderboard
- [ ] 2D Iteration used in the actual game
- [ ] Deployment will allow leaderboard to update for multiple users
This will be more complicated and more frontend-focused, we need to make sure that the leaderboard html "tab" works as intended and provides a good user experience. Possible features include viewing set number of users per page, filtering via column, viewing scores per user, etc.

By May 29th(Wednesday) we need to have everything debugged and **deployed** -- test saving scores and view leaderboard updates across computers.

## Each requirement:

Loops (Algorithmic):
Leaderboard data iteration will be done through sorting and searching, as well as displaying data successfully on frontend and serving DB data as JSON through the backend API.

Sorting / Searching (Algorithmic)
Show examples of sorting and searching using the backend of your project.. FYI, SQLAlchemy allows filtered selections and sorting. Additionally, you have sorting options discussed in tech talk.

Big(O)
Sorting and searching algorithms should be fast, will not exceed O(n) time complexity and this may be difficult due to there being so many scores associated with each user.

2D Iteration
2D Iteration done through game functionality and game end detection, displaying tetris blocks and updating positions as well as hit detection. 

Deployment (Full Stack):
Demonstration of multiple games with updating game leaderboards on both computers via Backend DB storage.

Example Leaderboard:
![92f6d37b57426fbb423864e3fa7c4bdd](https://github.com/spooketti/TetrisVS/assets/47793315/d2d8f714-78b8-4a42-b049-4c0ec47d2ee0)
